@startuml

entity "User" as user {
  id : number <<generated <<PK>>
  --
  dp_user_id: varchar(255)
  dp_dept_id: csb
  name: varchar(255)
  post: varchar(255)
  email: varchar(255)
  status: Active | Disable
  last_login_date: datetime
  created_by: varchar(255)
  modified_by: varchar(255)
  created_date: datetime
  modified_date: datetime
}

entity "Role" as role {
  id : number <<generated, PK>>
  --
  name: varchar(255)
  description: varchar(255)
  created_by: varchar(255)
  modified_by: varchar(255)
  created_date: datetime
  modified_date: datetime
}

entity "Permission" as permission {
  id : number <<generated, PK>>
  --
  name: varchar(255)
  key: varchar(255)
}

entity "User_Has_Role" as user_has_role {
  user_id: number <<PK, FK>>
  role_id: number <<PK, FK>>
}

entity "Role_Has_Permission" as role_has_permission {
  role_id: number <<PK, FK>>
  permission_id: <<PK, FK>>
}

entity "Exam_Profile" as exam_profile {
  id: number <<generated, PK>>
  --
  serial_no: varchar(255) <<generated EP000001..2..>>
  location: varchar(255)
  status: Freeze | Unfreeze
  created_by: varchar(255)
  modified_by: varchar(255)
  created_date: datetime
  modified_date: datetime
}

entity "Email_Template" as email_template {
  id: number <<generated, PK>>
  --
  key: varchar(255) <<unique>>
  description: varchar(255)
  cc: varchar(1000)
  bcc: varchar(1000)
  subject: varchar(1000)
  body: text
  created_by: varchar(255)
  modified_by: varchar(255)
  created_date: datetime
  modified_date: datetime
}

entity "Workflow_Notify_Email_Template" as workflow_notify_email_template {
  name: varchar(255) <<unique, PK>>
  email_template_id: number <<FK>>
}

entity "Eproof_Cert" as eproof_cert {
  cert_info_id: number <<FK>>
  eproof_id: varchar(20)
  key_name: varchar(8)
  uuid: varchar(100)
  version: number
  token: varchar(100)
  e_wallet_json: text
  e_cert_html: text
  url: varchar(1000)
}

entity "Cert_Pdf" as cert_pdf {
  id: number <<generated, PK>>
  --
  filename: varchar(255)
}

entity "Cert_Info" as cert_info {
  id: number <<generated, PK>>
  --
  exam_date: date
  can_serial: varchar(255)
  name: varchar(255)
  cname: varchar(255)
  hkid: varchar(255)
  passport: varchar(255)
  email: varchar(255)
  bl_grade: varchar(255)
  ue_grade: varchar(255)
  uc_grade: varchar(255)
  at_grade: varchar(255)
  remark: varchar(255)
  cert_stage: Imported | Generated\n| Sign_Issue | Notify | Completed
  status: Pending | Success | Fail
  on_hold: boolean
  on_hold_remark: text
  cert_pdf_id: number <<FK>>
  created_by: varchar(255)
  modified_by: varchar(255)
  created_date: datetime
  modified_date: datetime
}

entity "Cert_Info_Approve" as cert_info_approve {
  cert_info_id: number <<generated, PK>>
  --
  type: Appeal | Info_Update
  name: varchar(255)
  cname: varchar(255)
  hkid: varchar(255)
  passport: varchar(255)
  email: varchar(255)
  bl_grade: varchar(255)
  ue_grade: varchar(255)
  uc_grade: varchar(255)
  at_grade: varchar(255)
  remark: text
  pending_approve_by: varchar(255)
  done: boolean
  created_by: varchar(255)
  modified_by: varchar(255)
  created_date: datetime
  modified_date: datetime
}

entity "Candidate_Exam_Result_Before_2024" as candidate_exam_result_before_2024 {
  id: number <<generated, PK>>
  --
  exam_date: date
  can_serial: varchar(255)
  name: varchar(255)
  cname: varchar(255)
  hkid: varchar(255)
  passport: varchar(255)
  email: varchar(255)
  bl_grade: varchar(255)
  ue_grade: varchar(255)
  uc_grade: varchar(255)
  at_grade: varchar(255)
  created_by: varchar(255)
  modified_by: varchar(255)
  created_date: datetime
  modified_date: datetime
}

user ||--o{ user_has_role
user_has_role }o--|| role
role ||--o{ role_has_permission
role_has_permission }o--|| permission
email_template ||--o| workflow_notify_email_template
cert_info ||--o{ cert_info_approve
cert_info ||--o| cert_pdf
cert_info ||--o| eproof_cert
@enduml