#Database config
spring:
  datasource:
    url: jdbc:mariadb://192.168.2.184:3306/DB_PMS
    username: pms_admin
    password: P@ssw0rd
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
  sql:
    init:
      mode: never
      data-locations:
        - classpath:data_local.sql
  mail:
    host: mail.igsl-group.com
    port: 465
    username: dan.tai@igsl-group.com
    password: QLuD4bwe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    from: test@test.com
    protocol: smtps
  minio:
    url: http://192.168.2.238:9000
    accessKey: obt62qNqMuaCj98x
    secretKey: vTw0ZsnPD388llObsRE3DlMVJl2WycIo
    bucket: pms
    checkBucket: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health, metrics
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: false

messages:
  basename:
    path: messages/mailMessages

email:
  extend:
    list: ;

application:
  jwt:
    secretKey: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
    tokenPrefix: "Bearer "
    authorizationHeader: "Authorization"
    expirationSeconds: 7200

password:
  tokenExpirationAfterDays: 1

server:
  url: http://localhost:8080

security:
  whitelist: /api/*/auth/**, /api/*/user/forgotPassword, /api/*/user/resetPassword, /api/*/user/changePassword, /actuator/**

filter:
  config:
    urlPatterns: /api/*, /actuator/*

request:
  log:
    filter:
      maxPayloadLength: 500
      ignoredPaths:
        - /api/*/auth/**
        - /api/*/user/forgotPassword
        - /api/*/user/resetPassword
audit:
  trail:
    manager:
      include: DBAuditTrailManager, Slf4jLoggingAuditTrailManager

cronjob:
  audit:
    retention:
      cronExpression: 0 0 0 * * *
      days: 2556
  meetingWorkspace:
    retention:
      cronExpression: 0 0 0 * * *
      limit: 100
    purge:
      cronExpression: 0 0 0 * * *
  user:
    session:
      cleanup:
        cronExpression: 0 0 0 * * *
    password:
      expire:
        reminder:
          cronExpression: 0 0 0 * * *

search:
  meeting:
    url: /SOM/Meeting/SOM?meetingId=

login:
  allowMultipleLogin: true
  max:
    attempts: 3