#Database config
spring:
  datasource:
    url: jdbc:mariadb:loadbalance://t1vdbs-csbeprof-epdbu1-ha1.dbaas.gcisdctr.hksarg:19307,t1vdbs-csbeprof-epdbu1-ha2.dbaas.gcisdctr.hksarg:19307,t2vdbs-csbeprof-epdbu1-ha1.dbaas.gcisdctr.hksarg:19307,t2vdbs-csbeprof-epdbu1-ha2.dbaas.gcisdctr.hksarg:19307/eproof_db?useSSL=true&trustServerCertificate=true
    username: eproof_root
    password: P@ssw0rd1234$
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
  sql:
    init:
      mode: never
      data-locations:
        - classpath:data_local.sql
  messages:
    basename: i18n/messages
  mail:
    host: mail.igsl-group.com
    port: 465
    username: hong.cheung@igsl-group.com
    password: HongIgs_P@ssw0rd
    from: csbeproof@test.com
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health, metrics
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: false
    mail:
      enabled: false

application:
  jwt:
    secretKey: SldUX1NlY3JldEtleV8xMjM0NV9FUHJvb2ZAQ1NCX0lHU19FbmNyeXB0Snd0QDEyMzQ1Ng==
    tokenPrefix: "Bearer "
    authorizationHeader: "Authorization"
    expirationSeconds: 7200

password:
  tokenExpirationAfterDays: 1

server:
  url: https://eproofuat.csb.ccgo.hksarg
  servlet:
    context-path: /api/v1
security:
  #  whitelist: /api/*/auth/**, /api/*/user/forgotPassword, /api/*/user/resetPassword, /api/*/user/changePassword, /actuator/**
  whitelist: /api-docs/**,/sso,/test/**,/user/list

filter:
  config:
    urlPatterns: /api/*, /actuator/*

audit:
  trail:
    manager:
      include: DBAuditTrailManager, Slf4jLoggingAuditTrailManager

login:
  allowMultipleLogin: true
  max:
    attempts: 3

#swagger config
springdoc:
  api-docs:
    path: /api-docs/json
  swagger-ui:
    path: /api-docs/swagger
    display-request-duration: true

#logging config
#logging:
#  file:
#    path: logs/backend/
#    name: backend.log
#    max-age: 1d
#
#    root: INFO
#  logback:
#    rollingpolicy:
#      max-file-size: 10MB

document:
  #   Path for the temporary document to be generated.
  #   The generated document will be deleted immediately after generation
  #   Used for libre office conversion
  generate-temp-path: /vdisk/e-proof/tmp
  libreoffice-program-path: /opt/libreoffice24.2/program

minio:
  endpoint: https://csbeprof.t1cosg-obj001.gcisdctr.hksarg
  accessKey: Y3NiZXByb2ZfdXNlcg==
  secretKey: d023c3ada786f2218a635aee3bcf8b21
  bucket: eproof
  path:
    cert-record: /cert_record
    cert-renew-record: /cert_renew_record

mail:
  mode: SMTP
  health-check:
    enabled: true
    to: hong.cheung@igsl-group.com
    subject: EProof Mail Health Check
  whitelist:
    enabled: true
    email-list: hong.cheung@igsl-group.com

eproof-config:
  pass-template-type-id: 40f848bc-856c-4e6a-a1f1-a6b872efe752
  fail-template-type-id: 038424a4-be4e-418f-bdb4-dc4181d6ea16
  issuer-name-en: Civil Service Bureau
  issuer-name-tc: 公務員事務局
  issuer-did: "did:eproof:100cfb00-3029-474a-b794-2f735e1d3c1d"
  client-id: "CSB001"
  client-secret: "J+Y2aUo1FT2M&EpY$F@="
  url: "http://192.168.4.6:8080/api"
  pdfUrl: "https://eproofuat.csb.ccgo.hksarg/api/v1/eProof-pdf"
  otpUrl: "https://eproofuat.csb.ccgo.hksarg/api/v1/sendOTP"
  dataUrl: "https://eproofuat.csb.ccgo.hksarg/api/v1/eProof-data"
  downloadUrlPrefix: https://uat.eproof.gov.hk/ec/d?t=

thread-pool:
  scheduled-task:
    core-pool-size: 10
    max-pool-size: 20
    queue-capacity: 100
    thread-name-prefix: scheduled-task-thread-pool-
  normal:
    core-pool-size: 10
    max-pool-size: 20
    queue-capacity: 100
    thread-name-prefix: normal-thread-pool-

#second minute hour dayOfMonth month dayOfWeek
cron-expression:
  normal-email-sending: "-"




