#Database config
spring:
  datasource:
    url: jdbc:mariadb://192.168.2.227:3306/eproof
    username: root
    password: P@ssw0rd1234$
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
  sql:
    init:
      mode: never
      data-locations:
        - classpath:data_local.sql
  mail:
    host: mail.igsl-group.com
    port: 465
    username: hong.cheung@igsl-group.com
    password: HongIgs@P@ssw0rd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    from: test@test.com
    protocol: smtps
  minio:
    url: http://localhost:9000
    accessKey: obt62qNqMuaCj98x
    secretKey: vTw0ZsnPD388llObsRE3DlMVJl2WycIo
    bucket: pms
    checkBucket: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health, metrics
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: false

messages:
  basename:
    path: messages/mailMessages

email:
  extend:
    list: ;

application:
  jwt:
    secretKey: csbeproofrYv7#C2Tg$N!eLqJp9*F6@bZw8aS4dX1
    tokenPrefix: "Bearer "
    authorizationHeader: "Authorization"
    expirationSeconds: 7200

password:
  tokenExpirationAfterDays: 1

server:
  url: http://localhost:8080

security:
  whitelist: /api/*/auth/**, /api/*/user/forgotPassword, /api/*/user/resetPassword, /api/*/user/changePassword, /actuator/**

filter:
  config:
    urlPatterns: /api/*, /actuator/*


audit:
  trail:
    manager:
      include: DBAuditTrailManager, Slf4jLoggingAuditTrailManager


login:
  allowMultipleLogin: true
  max:
    attempts: 3