#Database config
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/e_proof?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: hdw1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
  sql:
    init:
      mode: never
      data-locations:
        - classpath:data_local.sql
  messages:
    basename: i18n/messages
    fallback-to-system-locale: false
  mail:
    host: mail.igsl-group.com
    port: 465
    username: hong.cheung@igsl-group.com
    password: HongIgs@P@ssw0rd
    from: cepf@test.com
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
            required: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  minio:
    url: http://localhost:9000
    accessKey: obt62qNqMuaCj98x
    secretKey: vTw0ZsnPD388llObsRE3DlMVJl2WycIo
    bucket: pms
    checkBucket: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health, metrics
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: false



email:
  extend:
    list: ;

application:
  jwt:
    secretKey: SldUX1NlY3JldEtleV8xMjM0NV9FUHJvb2ZAQ1NCX0lHU19FbmNyeXB0Snd0QDEyMzQ1Ng==
    tokenPrefix: "Bearer "
    authorizationHeader: "Authorization"
    expirationSeconds: 7200

password:
  tokenExpirationAfterDays: 1

server:
  url: http://localhost:8080
  servlet:
    context-path: /api/v1
security:
#  whitelist: /api/*/auth/**, /api/*/user/forgotPassword, /api/*/user/resetPassword, /api/*/user/changePassword, /actuator/**
  whitelist: /api-docs/**,/auth/**,/cert/**

filter:
  config:
    urlPatterns: /api/*, /actuator/*


audit:
  trail:
    manager:
      include: DBAuditTrailManager, Slf4jLoggingAuditTrailManager


login:
  allowMultipleLogin: true
  max:
    attempts: 3


#swagger config
springdoc:
  api-docs:
    path: /api-docs/json
  swagger-ui:
    path: /api-docs/swagger
    display-request-duration: true

#logging config
logging:
  file:
    path: logs/backend/
    name: backend.log
    max-age: 1d
  level:
    root: INFO
  logback:
    rollingpolicy:
      max-file-size: 10MB
