#Database config
spring:
  datasource:
    url: jdbc:mariadb:loadbalance://t1vdbs-csbeprof-epdbu1-ha1.dbaas.gcisdctr.hksarg:19307,t1vdbs-csbeprof-epdbu1-ha2.dbaas.gcisdctr.hksarg:19307,t2vdbs-csbeprof-epdbu1-ha1.dbaas.gcisdctr.hksarg:19307,t2vdbs-csbeprof-epdbu1-ha2.dbaas.gcisdctr.hksarg:19307/eproof_db?useSSL=true&trustServerCertificate=true
    username: eproof_root
    password: P@ssw0rd1234$
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
  sql:
    init:
      mode: never
      data-locations:
        - classpath:data_local.sql
  messages:
    basename: i18n/messages
  mail:
    host: mail.igsl-group.com
    port: 465
    username: hong.cheung@igsl-group.com
    password: HongIgs_P@ssw0rd
    from: csbeproof@test.com
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health, metrics
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: false
    mail:
      enabled: false

application:
  jwt:
    secretKey: SldUX1NlY3JldEtleV8xMjM0NV9FUHJvb2ZAQ1NCX0lHU19FbmNyeXB0Snd0QDEyMzQ1Ng==
    tokenPrefix: "Bearer "
    authorizationHeader: "Authorization"
    expirationSeconds: 7200

password:
  tokenExpirationAfterDays: 1

server:
  url: https://eproofuat.csb.ccgo.hksarg
  servlet:
    context-path: /api/v1
security:
  #  whitelist: /api/*/auth/**, /api/*/user/forgotPassword, /api/*/user/resetPassword, /api/*/user/changePassword, /actuator/**
  whitelist: /api-docs/**,/sso,/tempSso,/test/**,/user/list,/test,/eproof/sendOTP,/eproof/eProof-data,/eproof/eProof-pdf

filter:
  config:
    urlPatterns: /api/*, /actuator/*

audit:
  trail:
    manager:
      include: DBAuditTrailManager, Slf4jLoggingAuditTrailManager

login:
  allowMultipleLogin: true
  max:
    attempts: 3

#swagger config
springdoc:
  api-docs:
    path: /api-docs/json
  swagger-ui:
    path: /api-docs/swagger
    display-request-duration: true

#logging config
#logging:
#  file:
#    path: logs/backend/
#    name: backend.log
#    max-age: 1d
#
#    root: INFO
#  logback:
#    rollingpolicy:
#      max-file-size: 10MB

document:
  #   Path for the temporary document to be generated.
  #   The generated document will be deleted immediately after generation
  #   Used for libre office conversion
  generate-temp-path: /vdisk/e-proof/tmp
  libreoffice-program-path: /opt/libreoffice24.2/program

minio:
  endpoint: https://csbeprof.t1cosg-obj001.gcisdctr.hksarg
  accessKey: Y3NiZXByb2ZfdXNlcg==
  secretKey: d023c3ada786f2218a635aee3bcf8b21
  bucket: eproof
  path:
    cert-record: /cert_record
    cert-renew-record: /cert_renew_record

mail:
  mode: SMTP
  health-check:
    enabled: true
    to: hong.cheung@igsl-group.com
    subject: EProof Mail Health Check
  whitelist:
    enabled: true
    email-list: hong.cheung@igsl-group.com
  include:
    attachement: Y

eproof-config:
  limit-for-batch-issuance: 5000
  pass-template-type-id: 40f848bc-856c-4e6a-a1f1-a6b872efe752
  fail-template-type-id: 038424a4-be4e-418f-bdb4-dc4181d6ea16
  issuer-name-en: Civil Service Bureau
  issuer-name-tc: 公務員事務局
  issuer-did: "did:eproof:100cfb00-3029-474a-b794-2f735e1d3c1d"
  client-id: "CSB001"
  client-secret: "J+Y2aUo1FT2M&EpY$F@="
  url: "http://192.168.4.6:8080/api"
  pdfUrl: "https://eproofuat.csb.ccgo.hksarg/api/v1/eproof/eProof-pdf"
  otpUrl: "https://eproofuat.csb.ccgo.hksarg/api/v1/eproof/sendOTP"
  dataUrl: "https://eproofuat.csb.ccgo.hksarg/api/v1/eproof/eProof-data"
  downloadUrlPrefix: https://uat-download.eproof.gov.hk/en/d?t=

thread-pool:
  scheduled-task:
    core-pool-size: 10
    max-pool-size: 20
    queue-capacity: 100
    thread-name-prefix: scheduled-task-thread-pool-
  normal:
    core-pool-size: 10
    max-pool-size: 20
    queue-capacity: 100
    thread-name-prefix: normal-thread-pool-

#second minute hour dayOfMonth month dayOfWeek
cron-expression:
  normal-email-sending: "-"
  refresh-eproof-access-token: "0 0/30 * * * *"
  upload-today-batch-xml-to-gcis: "0 0 1 * * *"
  schedule-today-batch-email: "0 0 6 * * *"
  enquire-and-update-schedule-status: "0 0 7-12 * * *"

gcis-shared-service:
  batch-email:
    split-size: 5000
    local-temporary-xml-folder-path: /vdisk/e-proof/tmp
    upload-trial-times: 2
    schedule-trial-times: 2
    projectId: CSBEP
  enabled: true
  emailWhitelist:
    enabled: true
    toList: hong.cheung@igsl-group.com, wilfred.lai@igsl-group.com
  property:
    path: C:\Users\IGS\Desktop\projects\csb-eproof\backend\src\main\resources\proximity.properties
  keystore:
    path: C:\Users\IGS\Desktop\projects\csb-eproof\backend\src\main\resources\eproofuat.csb.ccgo.hksarg.p12
    alias: dsign
    password: P@ssw0rd1234$
  notiSvc:
    endPointName: NOTI_SENDER_RESTFUL_END_POINT
    endPointUrl: https://ttgd-xmlfw.egisdctr.hksarg:9444/messaging/ssl/RESTful/csb.csbep.app001-ogcio.egis.nt001-NotiSenderRest
    batchUploadEndPointName: BATCH_UPLOAD_RESTFUL_END_POINT
    batchUploadEndPointUrl: https://ttgd-xmlfw.egisdctr.hksarg:9444/messaging/ssl/RESTful/csb.csbep.app001-ogcio.egis.nt001-BatchUploadRest
    scheduleEndPointName: SCHEDULE_RESTFUL_END_POINT
    scheduleEndPointUrl: https://ttgd-xmlfw.egisdctr.hksarg:9444/messaging/ssl/RESTful/csb.csbep.app001-ogcio.egis.nt001-ScheduleRest
    batchEnquireEndPointName: BATCH_ENQ_RESTFUL_END_POINT
    batchEnquireEndPointUrl: https://ttgd-xmlfw.egisdctr.hksarg:9444/messaging/ssl/RESTful/csb.csbep.app001-ogcio.egis.nt001-BatchEnqRest
    scheduleEnquireEndPointName: SCHE_ENQ_RESTFUL_END_POINT
    scheduleEnquireEndPointUrl: https://ttgd-xmlfw.egisdctr.hksarg:9444/messaging/ssl/RESTful/csb.csbep.app001-ogcio.egis.nt001-ScheEnqRest



