export const PERMISSION_KEY = {
  USER_MAINTENANCE: 'USER_MAINTENANCE',
  USER_VIEWER: 'USER_VIEWER',
  ACCESS_CONTROL_MAINTENANCE: 'ACCESS_CONTROL_MAINTENANCE',
  ACCESS_CONTROL_VIEWER: 'ACCESS_CONTROL_VIEWER',
  MEETING_WORKSPACE_MAINTENANCE: 'MEETING_WORKSPACE_MAINTENANCE',
  APPROVE: 'APPROVE',
  BD_TABLE_MAINTENANCE: 'BD_TABLE_MAINTENANCE',
  BD_TABLE_VIEWER: 'BD_TABLE_VIEWER',
  CONFIGURATION_MAINTENANCE: 'CONFIGURATION_MAINTENANCE',
  AUDIT_TRAIL_VIEWER: 'AUDIT_TRAIL_VIEWER',
  SESSION_CONTROL_MAINTENANCE: 'SESSION_CONTROL_MAINTENANCE',
  GROUP_TABLE_VIEWER: 'GROUP_TABLE_VIEWER',
  GROUP_TABLE_MAINTENANCE: 'GROUP_TABLE_MAINTENANCE'
}